<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 static/models/OfficeAssets_free.glb --suspense --draco --shadows --transform --resolution=4096 --simplify --keepnames --root=models/
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useSuspense } from '@threlte/extras'

  export const ref = new Group()

  const suspend = useSuspense()

  const gltf = suspend(useGltf('models/OfficeAssets_free-transformed.glb', { useDraco: true }))

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh
      name="Walls"
      castShadow
      receiveShadow
      geometry={gltf.nodes.Walls.geometry}
      material={gltf.materials.concrete_layers_02}
      position={[-39.74, -6.05, 33.01]}
      rotation={[Math.PI, 0, 0]}
    />
    <T.Mesh
      name="Walls001"
      castShadow
      receiveShadow
      geometry={gltf.nodes.Walls001.geometry}
      material={gltf.materials.concrete_layers_02}
      position={[-5.84, -37.61, 33.01]}
      rotation={[Math.PI, 0, Math.PI / 2]}
    />
    <T.Mesh
      name="Walls002"
      castShadow
      receiveShadow
      geometry={gltf.nodes.Walls002.geometry}
      material={gltf.materials.concrete_layers_02}
      position={[-6.67, 71.85, 33.01]}
      rotation={[Math.PI, 0, Math.PI / 2]}
    />
    <T.Mesh
      name="Notepad"
      castShadow
      receiveShadow
      geometry={gltf.nodes.Notepad.geometry}
      material={gltf.materials.M_Office_PinBoard_Photo_Notepad_1024}
      position={[3.64, -2.97, 32.69]}
      rotation={[-0.01, 1.39, 0.01]}
      scale={[17.65, 6.36, 17.65]}
    />
    <T.Mesh
      name="PhotoFrame_10x15"
      castShadow
      receiveShadow
      geometry={gltf.nodes.PhotoFrame_10x15.geometry}
      material={gltf.materials.M_Office_PinBoard_Photo_Notepad_1024}
      position={[6.95, -2.97, 44.34]}
      rotation={[Math.PI / 2, 0, -1.81]}
      scale={17.65}
    />
    <T.Mesh
      name="PinBoard"
      castShadow
      receiveShadow
      geometry={gltf.nodes.PinBoard.geometry}
      material={gltf.materials.M_Office_PinBoard_Photo_Notepad_1024}
      position={[-37.83, 23.86, 51]}
      rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      scale={17.65}
    >
      <T.Mesh
        name="Paper_Fax1"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Paper_Fax1.geometry}
        material={gltf.materials.M_Office_PinBoard_Photo_Notepad_1024}
        position={[0.43, 0.04, -0.44]}
        rotation={[-0.02, -0.02, 0]}
      />
      <T.Mesh
        name="Paper_Fax2"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Paper_Fax2.geometry}
        material={gltf.materials.M_Office_PinBoard_Photo_Notepad_1024}
        position={[-0.44, 0.04, 0.07]}
        rotation={[-0.03, 0.04, 0]}
      />
      <T.Mesh
        name="Paper_Note"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Paper_Note.geometry}
        material={gltf.materials.M_Office_PinBoard_Photo_Notepad_1024}
        position={[-0.12, 0.03, -0.37]}
        rotation={[-0.05, -0.05, 0]}
      />
      <T.Mesh
        name="Photo_Child"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Photo_Child.geometry}
        material={gltf.materials.M_Office_PinBoard_Photo_Notepad_1024}
        position={[0.44, 0.03, 0.2]}
        rotation={[-0.07, 0.06, 0]}
      />
      <T.Mesh
        name="Photo_Family"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Photo_Family.geometry}
        material={gltf.materials.M_Office_PinBoard_Photo_Notepad_1024}
        position={[-0.58, 0.03, -0.5]}
        rotation={[-0.03, -0.06, 0]}
      />
      <T.Mesh
        name="Pin_Big1"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Pin_Big1.geometry}
        material={gltf.materials.M_Office_PinBoard_Photo_Notepad_1024}
        position={[0.19, 0.04, -0.43]}
        rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
        scale={2.63}
      />
      <T.Mesh
        name="Pin_Big2"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Pin_Big2.geometry}
        material={gltf.materials.M_Office_PinBoard_Photo_Notepad_1024}
        position={[-0.59, 0.04, -0.47]}
        rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
        scale={2.63}
      />
      <T.Mesh
        name="Pin_Big2001"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Pin_Big2001.geometry}
        material={gltf.materials.M_Office_PinBoard_Photo_Notepad_1024}
        position={[0.68, 0.04, -0.42]}
        rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
        scale={2.63}
      />
      <T.Mesh
        name="Pin_Flat1"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Pin_Flat1.geometry}
        material={gltf.materials.M_Office_PinBoard_Photo_Notepad_1024}
        position={[-0.44, 0.04, 0.09]}
        rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
        scale={2.63}
      />
      <T.Mesh
        name="Pin_Flat1001"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Pin_Flat1001.geometry}
        material={gltf.materials.M_Office_PinBoard_Photo_Notepad_1024}
        position={[0.48, 0.04, 0.23]}
        rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
        scale={2.63}
      />
      <T.Mesh
        name="Pin_Flat2"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Pin_Flat2.geometry}
        material={gltf.materials.M_Office_PinBoard_Photo_Notepad_1024}
        position={[-0.12, 0.04, -0.36]}
        rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
        scale={2.63}
      />
    </T.Mesh>
    <T.Mesh
      name="Cigarette_Normal"
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cigarette_Normal.geometry}
      material={gltf.materials.M_Sigarettes_512}
      position={[9.11, -2.8, 18.9]}
      rotation={[1, 0.42, 1]}
      scale={23.18}
    />
    <T.Mesh
      name="CigarettePack_Blue"
      castShadow
      receiveShadow
      geometry={gltf.nodes.CigarettePack_Blue.geometry}
      material={gltf.materials.M_Sigarettes_512}
      position={[4.53, -2.54, 19.25]}
      rotation={[Math.PI, -1.19, -1.89]}
      scale={23.18}
    />
    <T.Mesh
      name="Ashtray"
      castShadow
      receiveShadow
      geometry={gltf.nodes.Ashtray.geometry}
      material={gltf.materials.M_Sigarettes_512}
      position={[9.38, -2.97, 11.76]}
      scale={46.37}
    />
    <T.Mesh
      name="Cigarette_Stub_Bent"
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cigarette_Stub_Bent.geometry}
      material={gltf.materials.M_Sigarettes_512}
      position={[7.51, -1.99, 9.89]}
      rotation={[-1.45, -0.19, -2.33]}
      scale={23.18}
    />
    <T.Mesh
      name="Cigarette_Stub_Straight"
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cigarette_Stub_Straight.geometry}
      material={gltf.materials.M_Sigarettes_512}
      position={[11.39, -1.88, 14.38]}
      rotation={[-1.7, -0.14, 0.34]}
      scale={23.18}
    />
    <T.Mesh
      name="Ashtray_Ash"
      castShadow
      receiveShadow
      geometry={gltf.nodes.Ashtray_Ash.geometry}
      material={gltf.materials.M_Sigarettes_512}
      position={[9.38, -2.56, 11.76]}
      scale={[46.37, 20.87, 46.37]}
    />
    <T.Mesh
      name="CigarettePack_Brown"
      castShadow
      receiveShadow
      geometry={gltf.nodes.CigarettePack_Brown.geometry}
      material={gltf.materials.M_Sigarettes_512}
      position={[7.73, -2.54, 17.05]}
      rotation={[0, -0.57, 1.57]}
      scale={23.18}
    />
    <T.Mesh
      name="Table_Rough"
      castShadow
      receiveShadow
      geometry={gltf.nodes.Table_Rough.geometry}
      material={gltf.materials.M_Table_2048}
      position={[-3.32, -37.16, 3.51]}
      scale={46.37}
    />
    <T.Group name="TapeRecorder" position={[-11.58, -2.97, 37.46]} rotation={[-Math.PI, 1.01, -Math.PI]} scale={46.37}>
      <T.Mesh
        name="Circle005"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Circle005.geometry}
        material={gltf.materials.M_TapeRecorder_1024}
      />
      <T.Mesh
        name="Circle005_1"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Circle005_1.geometry}
        material={gltf.materials.M_TapeRecorder_Tape_Rotors_Glass_1024}
      />
    </T.Group>
    <T.Mesh
      name="Microphone"
      castShadow
      receiveShadow
      geometry={gltf.nodes.Microphone.geometry}
      material={gltf.materials.M_TapeRecorder_Tape_Rotors_Glass_1024}
      position={[-4.76, -2.97, 18.73]}
      rotation={[0, 0.28, 0]}
      scale={46.37}
    />
    <T.Mesh
      name="Vent"
      castShadow
      receiveShadow
      geometry={gltf.nodes.Vent.geometry}
      material={gltf.materials.M_Vent_1024}
      position={[-36.66, 55.72, 46.6]}
      scale={46.37}
    >
      <T.Mesh
        name="FanSupport"
        castShadow
        receiveShadow
        geometry={gltf.nodes.FanSupport.geometry}
        material={gltf.materials.M_Vent_1024}
        position={[0.05, -0.01, 0]}
      >
        <T.Mesh
          name="Vent_Fan"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Vent_Fan.geometry}
          material={gltf.materials.M_Vent_1024}
          rotation={[Math.PI / 3, 0, 0]}
        />
      </T.Mesh>
      <T.Mesh
        name="Nut"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Nut.geometry}
        material={gltf.materials.M_Vent_1024}
        position={[0, 0.16, 0.24]}
      />
      <T.Mesh
        name="Vend_AirDuct"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Vend_AirDuct.geometry}
        material={gltf.materials.M_Vent_1024}
        position={[-0.01, 0, 0]}
      />
      <T.Mesh
        name="Vent_Cover_Frame"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Vent_Cover_Frame.geometry}
        material={gltf.materials.M_Vent_1024}
        position={[0.13, 0, 0]}
      >
        <T.Mesh
          name="Vent_Cover"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Vent_Cover.geometry}
          material={gltf.materials.M_Vent_1024}
          position={[0, -0.11, 0]}
        />
        <T.Mesh
          name="Vent_Filter"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Vent_Filter.geometry}
          material={gltf.materials.M_Vent_1024}
          position={[-0.16, 0, 0]}
        >
          <T.Mesh
            name="Vent_Filter_LinesH"
            castShadow
            receiveShadow
            geometry={gltf.nodes.Vent_Filter_LinesH.geometry}
            material={gltf.materials.M_Vent_1024}
            position={[0.01, 0.01, 0]}
          />
          <T.Mesh
            name="Vent_Filter_LinesV"
            castShadow
            receiveShadow
            geometry={gltf.nodes.Vent_Filter_LinesV.geometry}
            material={gltf.materials.M_Vent_1024}
            position={[0.13, -0.02, 0.19]}
          />
        </T.Mesh>
      </T.Mesh>
    </T.Mesh>
    <T.Mesh
      name="Poster_Crumpled"
      castShadow
      receiveShadow
      geometry={gltf.nodes.Poster_Crumpled.geometry}
      material={gltf.materials.Poster_1024}
      position={[-36.19, 35.26, 10.24]}
      rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      scale={[28.69, 14.35, 28.69]}
    />
    <T.Mesh
      name="PhotoFrame2"
      castShadow
      receiveShadow
      geometry={gltf.nodes.PhotoFrame2.geometry}
      material={gltf.materials.PhotoFrame_20x30_likeA4_512}
      position={[-36.54, 25.18, -33.04]}
      rotation={[0, -Math.PI / 2, 0]}
      scale={[46.01, 46.01, 51.84]}
    />
    <T.Mesh
      name="Notebook"
      castShadow
      receiveShadow
      geometry={gltf.nodes.Notebook.geometry}
      material={gltf.materials.M_Clipboard_Notepad_1024}
      position={[3.02, -2.97, 26.92]}
      rotation={[0, 0.32, Math.PI / 2]}
      scale={46.37}
    />
    <T.Mesh
      name="Chair"
      castShadow
      receiveShadow
      geometry={gltf.nodes.Chair.geometry}
      material={gltf.materials.M_OfficeStool_Bin_2048}
      position={[43.74, -37.03, -11.37]}
      rotation={[Math.PI, -0.42, Math.PI]}
      scale={[57.28, 46.37, 57.28]}
    />
    <T.Mesh
      name="Lamp01"
      castShadow
      receiveShadow
      geometry={gltf.nodes.Lamp01.geometry}
      material={gltf.materials['M_Lamps_CCTV_2048.001']}
      position={[-15, -2.97, 21.67]}
      rotation={[0, 0.45, 0]}
      scale={46.37}
    >
      <T.Mesh
        name="Lamp02001"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Lamp02001.geometry}
        material={gltf.materials['M_Lamps_CCTV_2048.001']}
        position={[0, 0.06, 0]}
        rotation={[0, 0, 0.81]}
      >
        <T.Mesh
          name="Lamp02002"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Lamp02002.geometry}
          material={gltf.materials['M_Lamps_CCTV_2048.001']}
          position={[0, 0.12, 0]}
          rotation={[0, 0, -0.98]}
        >
          <T.Mesh
            name="Lamp02"
            castShadow
            receiveShadow
            geometry={gltf.nodes.Lamp02.geometry}
            material={gltf.materials['M_Lamps_CCTV_2048.001']}
            position={[0, 0.28, 0]}
            rotation={[0, 0, -0.49]}
          >
            <T.Mesh
              name="Lamp_Holder001"
              castShadow
              receiveShadow
              geometry={gltf.nodes.Lamp_Holder001.geometry}
              material={gltf.materials['M_Lamps_CCTV_2048.001']}
              position={[0, 0.37, 0]}
              rotation={[0, 0, -0.6]}
            >
              <T.Mesh
                name="Lamp_Shade001"
                castShadow
                receiveShadow
                geometry={gltf.nodes.Lamp_Shade001.geometry}
                material={gltf.materials['M_Lamps_CCTV_2048.001']}
                position={[0, 0.08, 0]}
              />
            </T.Mesh>
          </T.Mesh>
        </T.Mesh>
      </T.Mesh>
    </T.Mesh>
    <T.Mesh
      name="PhotoFrame_10x15001"
      castShadow
      receiveShadow
      geometry={gltf.nodes.PhotoFrame_10x15001.geometry}
      material={gltf.materials.M_Office_PinBoard_Photo_Notepad_1024}
      position={[-37.33, 9.98, -13.99]}
      rotation={[1.59, -0.18, -1.53]}
      scale={17.65}
    />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
