<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 static/models/lumen64_final.glb --shadows --transform --resolution=4096 --simplify --keepnames --root=models/
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'
  import FrontControlPanel from '$lib/components/models/FrontControlPanel.svelte';
	import { onMount } from 'svelte';

  export const ref = new Group()

  const gltf = useGltf('models/lumen64_final-transformed.glb', { useDraco: true })
  export const { actions, mixer } = useGltfAnimations(gltf, ref)


    gltf.then(( model ) => {
      function alphaFix(material){
        material.depthWrite = true;
        material.depthTest = true;
        material.opacity = 1;
        material.alphaToCoverage = true;
        material.blending = 0;
        console.log(material)
      }
      function metalFix(material){
        material.metalness = 0.8;
        material.roughness = 0.5;
      }
      function roughnessFix(material){
        material.roughness = 0;
      }
      function zIndexFix(material){
        material.depthWrite = true;
        material.depthTest = true;
      }
      zIndexFix(model.materials.cable_bolt_canvas)
      alphaFix(model.materials.glass);
      metalFix(model.materials.big_details);
      roughnessFix(model.materials.panel_and_bottom_details);

    })

    onMount(() => {
      let actionsBool = false;
       //launch every animation 
      document.addEventListener('keydown', (e) => {
        const animationNotToStart = [
          'switchStickAction' 
        ]
        if (e.key === 'a') {
          actionsBool = !actionsBool
          console.log($actions)
            const tempActions = Object.keys($actions)
            animationNotToStart.forEach((actionToBan) => {
              tempActions.splice(tempActions.indexOf(actionToBan), 1)
            })
            tempActions.forEach(action => {
              if(actionsBool){
                $actions[action].paused = false
                $actions[action]?.play()
                $actions[action]?.fadeIn(2)
                
              }else{
                $actions[action]?.halt(2)
              }
            });
        }
      })
    })

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group name="Scene">

      <FrontControlPanel {gltf} />
      <T.Mesh
        name="bottom_base001"
        castShadow
        receiveShadow
        geometry={gltf.nodes.bottom_base001.geometry}
        material={gltf.materials.big_details}
        position={[13.59, 0, 0.08]}
        rotation={[-Math.PI, 0, 0]}
      />
      <T.Mesh
        name="top_base001"
        castShadow
        receiveShadow
        geometry={gltf.nodes.top_base001.geometry}
        material={gltf.materials.big_details}
        position={[8.09, 6.29, 0.09]}
      />
      <T.Mesh
        name="stand001"
        castShadow
        receiveShadow
        geometry={gltf.nodes.stand001.geometry}
        material={gltf.materials.big_details}
        position={[13.1, 0, 0.08]}
      />
      <T.Mesh
        name="fence_count001"
        castShadow
        receiveShadow
        geometry={gltf.nodes.fence_count001.geometry}
        material={gltf.materials.big_details}
        position={[13.59, 0, 0.08]}
        rotation={[-Math.PI, 0, 0]}
      />
      <T.Mesh
        name="side_fence001"
        castShadow
        receiveShadow
        geometry={gltf.nodes.side_fence001.geometry}
        material={gltf.materials.big_details}
        position={[13.59, 0, 0.08]}
        rotation={[-Math.PI, 0, Math.PI / 2]}
      />
      <T.Mesh
        name="gears001"
        castShadow
        receiveShadow
        geometry={gltf.nodes.gears001.geometry}
        material={gltf.materials.big_details}
        position={[8.01, 6.29, 0.09]}
      />
      <T.Mesh
        name="count001"
        castShadow
        receiveShadow
        geometry={gltf.nodes.count001.geometry}
        material={gltf.materials.big_details}
        position={[1.07, 0.61, 0]}
        rotation={[0, 0, -Math.PI / 2]}
      />
      <T.Mesh
        name="cable001"
        castShadow
        receiveShadow
        geometry={gltf.nodes.cable001.geometry}
        material={gltf.materials.big_details}
        position={[0.98, 0.61, 0]}
      />
      <T.Mesh
        name="input001"
        castShadow
        receiveShadow
        geometry={gltf.nodes.input001.geometry}
        material={gltf.materials.big_details}
        position={[-5.12, -0.73, -5.86]}
        rotation={[2.05, -0.21, -0.38]}
      />
      <T.Mesh
        name="handle_ram001"
        castShadow
        receiveShadow
        geometry={gltf.nodes.handle_ram001.geometry}
        material={gltf.materials.big_details}
        position={[8.48, 5.26, 0.09]}
      />
      <T.Mesh
        name="strape001"
        castShadow
        receiveShadow
        geometry={gltf.nodes.strape001.geometry}
        material={gltf.materials.big_details}
        position={[8.04, 6.33, 0.09]}
        rotation={[0, 1.57, 0]}
      />
      <T.Mesh
        name="conect_handle001"
        castShadow
        receiveShadow
        geometry={gltf.nodes.conect_handle001.geometry}
        material={gltf.materials.big_details}
        position={[8.15, 6.34, 0.09]}
      />
      <T.Mesh
        name="img_set_conector001"
        castShadow
        receiveShadow
        geometry={gltf.nodes.img_set_conector001.geometry}
        material={gltf.materials.big_details}
        position={[8.09, 6.29, 0.09]}
      />
      <T.Mesh
        name="top_audio_conect001"
        castShadow
        receiveShadow
        geometry={gltf.nodes.top_audio_conect001.geometry}
        material={gltf.materials.big_details}
        position={[8.09, 6.29, 0.09]}
      />
      <T.Mesh
        name="bottom_audio_conect001"
        castShadow
        receiveShadow
        geometry={gltf.nodes.bottom_audio_conect001.geometry}
        material={gltf.materials.big_details}
        position={[8.09, 6.29, 0.09]}
      />
      <T.Mesh
        name="border001"
        castShadow
        receiveShadow
        geometry={gltf.nodes.border001.geometry}
        material={gltf.materials.big_details}
        position={[13.59, 0, 0.08]}
        rotation={[-Math.PI, 0, 0]}
      />
      <T.Mesh
        name="frpm_main_body001"
        castShadow
        receiveShadow
        geometry={gltf.nodes.frpm_main_body001.geometry}
        material={gltf.materials.panel_and_bottom_details}
        position={[7.02, 2.05, 0.18]}
        rotation={[Math.PI, 0, Math.PI / 2]}
      />
      <T.Mesh
        name="made_in_plate001"
        castShadow
        receiveShadow
        geometry={gltf.nodes.made_in_plate001.geometry}
        material={gltf.materials.panel_and_bottom_details}
        position={[1.9, 3.17, 0]}
      />
      <T.Mesh
        name="main_panel_plate001"
        castShadow
        receiveShadow
        geometry={gltf.nodes.main_panel_plate001.geometry}
        material={gltf.materials.panel_and_bottom_details}
        position={[16.73, 4.39, 2.35]}
        rotation={[-3.14, 0, 0]}
      />
      <T.Mesh
        name="voltage_warning001"
        castShadow
        receiveShadow
        geometry={gltf.nodes.voltage_warning001.geometry}
        material={gltf.materials.panel_and_bottom_details}
        position={[14.81, 3.32, -0.43]}
      />
      <T.Mesh
        name="back_set_fan001"
        castShadow
        receiveShadow
        geometry={gltf.nodes.back_set_fan001.geometry}
        material={gltf.materials.panel_and_bottom_details}
        position={[13.59, 0, 0.08]}
      />
      <T.Mesh
        name="fan001"
        castShadow
        receiveShadow
        geometry={gltf.nodes.fan001.geometry}
        material={gltf.materials.panel_and_bottom_details}
        position={[1.36, 3.22, 4.99]}
      />
      <T.Mesh
        name="fan_fence_border001"
        castShadow
        receiveShadow
        geometry={gltf.nodes.fan_fence_border001.geometry}
        material={gltf.materials.panel_and_bottom_details}
        position={[13.59, 0, 0.08]}
        rotation={[-Math.PI, 0, 0]}
      />
      <T.Mesh
        name="fan_magnit001"
        castShadow
        receiveShadow
        geometry={gltf.nodes.fan_magnit001.geometry}
        material={gltf.materials.panel_and_bottom_details}
        position={[13.59, 0, 0.08]}
        rotation={[-Math.PI, 0, -Math.PI / 2]}
      />
      <T.Mesh
        name="fan002"
        castShadow
        receiveShadow
        geometry={gltf.nodes.fan002.geometry}
        material={gltf.materials.panel_and_bottom_details}
        position={[1.36, 3.22, -4.84]}
      />
      <T.Mesh
        name="cpu_body001"
        castShadow
        receiveShadow
        geometry={gltf.nodes.cpu_body001.geometry}
        material={gltf.materials.panel_and_bottom_details}
        position={[7.02, 2.05, 0.18]}
      />
      <T.Mesh
        name="cpu_info001"
        castShadow
        receiveShadow
        geometry={gltf.nodes.cpu_info001.geometry}
        material={gltf.materials.panel_and_bottom_details}
        position={[7.02, 2.02, 0.18]}
      />
      <T.Mesh
        name="from_cpu001"
        castShadow
        receiveShadow
        geometry={gltf.nodes.from_cpu001.geometry}
        material={gltf.materials.panel_and_bottom_details}
        position={[7.02, 2.05, 0.18]}
        rotation={[0, 0, -Math.PI / 2]}
      />
      <T.Mesh
        name="cable_conector_mini001"
        castShadow
        receiveShadow
        geometry={gltf.nodes.cable_conector_mini001.geometry}
        material={gltf.materials.panel_and_bottom_details}
        position={[7.02, 1.97, 0.18]}
      />
      <T.Mesh
        name="1_uv_Cylinder001"
        castShadow
        receiveShadow
        geometry={gltf.nodes['1_uv_Cylinder001'].geometry}
        material={gltf.materials.panel_and_bottom_details}
        position={[6.62, 2.82, 0.75]}
      />
      <T.Mesh
        name="Cylinder009"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cylinder009.geometry}
        material={gltf.materials.panel_and_bottom_details}
        position={[7.38, 2.73, 0.09]}
      />
      <T.Mesh
        name="Cylinder012"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cylinder012.geometry}
        material={gltf.materials.panel_and_bottom_details}
        position={[6.98, 2.72, -0.4]}
      />
      <T.Mesh
        name="Cylinder001"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cylinder001.geometry}
        material={gltf.materials.panel_and_bottom_details}
        position={[6.49, 2.83, -0.03]}
      />
      <T.Mesh
        name="Cylinder004"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cylinder004.geometry}
        material={gltf.materials.panel_and_bottom_details}
        position={[7.42, 2.83, 0.64]}
      />
      <T.Mesh
        name="Cylinder005"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cylinder005.geometry}
        material={gltf.materials.panel_and_bottom_details}
        position={[6.93, 2.83, 0.23]}
      />
      <T.Mesh
        name="Cylinder006"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cylinder006.geometry}
        material={gltf.materials.panel_and_bottom_details}
        position={[7.72, 2.83, -0.26]}
      />
      <T.Mesh
        name="main_winding001"
        castShadow
        receiveShadow
        geometry={gltf.nodes.main_winding001.geometry}
        material={gltf.materials.panel_and_bottom_details}
        position={[3.41, 2.75, 0.21]}
      />
      <T.Mesh
        name="trans_count_plate001"
        castShadow
        receiveShadow
        geometry={gltf.nodes.trans_count_plate001.geometry}
        material={gltf.materials.panel_and_bottom_details}
        position={[3.41, 2.75, 0.1]}
      />
      <T.Mesh
        name="trans_podium001"
        castShadow
        receiveShadow
        geometry={gltf.nodes.trans_podium001.geometry}
        material={gltf.materials.panel_and_bottom_details}
        position={[3.46, 1.32, 0.06]}
      />
      <T.Mesh
        name="winding001"
        castShadow
        receiveShadow
        geometry={gltf.nodes.winding001.geometry}
        material={gltf.materials.panel_and_bottom_details}
        position={[3.41, 2.33, 0.1]}
      />
      <T.Mesh
        name="base_tubes002"
        castShadow
        receiveShadow
        geometry={gltf.nodes.base_tubes002.geometry}
        material={gltf.materials.panel_and_bottom_details}
        position={[13.59, 0, 0.08]}
      />
      <T.Mesh
        name="1_cable_clips_uv001"
        castShadow
        receiveShadow
        geometry={gltf.nodes['1_cable_clips_uv001'].geometry}
        material={gltf.materials.panel_and_bottom_details}
        position={[2.13, 6.82, 1.8]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <T.Mesh
        name="cable_clips002"
        castShadow
        receiveShadow
        geometry={gltf.nodes.cable_clips002.geometry}
        material={gltf.materials.panel_and_bottom_details}
        position={[2.18, 7.62, 0.1]}
      />
      <T.Mesh
        name="cable_clips003"
        castShadow
        receiveShadow
        geometry={gltf.nodes.cable_clips003.geometry}
        material={gltf.materials.panel_and_bottom_details}
        position={[2.16, 6.82, -1.5]}
        rotation={[Math.PI / 2, 0, -Math.PI]}
      />
      <T.Mesh
        name="Cube001"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cube001.geometry}
        material={gltf.materials.panel_and_bottom_details}
        position={[2.15, 6.02, 0.1]}
        rotation={[Math.PI, 0, 0]}
      />
      <T.Mesh
        name="voltage_hub001"
        castShadow
        receiveShadow
        geometry={gltf.nodes.voltage_hub001.geometry}
        material={gltf.materials.panel_and_bottom_details}
        position={[2.39, 6.79, 0.15]}
      />
      <T.Mesh
        name="1_uv_number_plate_l001"
        castShadow
        receiveShadow
        geometry={gltf.nodes['1_uv_number_plate_l001'].geometry}
        material={gltf.materials.panel_and_bottom_details}
        position={[16.67, 3.92, 7.03]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <T.Mesh
        name="number_plate_r001"
        castShadow
        receiveShadow
        geometry={gltf.nodes.number_plate_r001.geometry}
        material={gltf.materials.panel_and_bottom_details}
        position={[16.67, 3.92, 6.24]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <T.Mesh
        name="shaft001"
        castShadow
        receiveShadow
        geometry={gltf.nodes.shaft001.geometry}
        material={gltf.materials.panel_and_bottom_details}
        position={[16.67, 3.92, 6.89]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <T.Mesh
        name="cpu_usage_label001"
        castShadow
        receiveShadow
        geometry={gltf.nodes.cpu_usage_label001.geometry}
        material={gltf.materials.panel_and_bottom_details}
        position={[13.59, 0, 0.08]}
        rotation={[-Math.PI, 0, 0]}
      />
      <T.Mesh
        name="cpu_usage_count001"
        castShadow
        receiveShadow
        geometry={gltf.nodes.cpu_usage_count001.geometry}
        material={gltf.materials.panel_and_bottom_details}
        position={[13.58, 0, 9.25]}
        rotation={[-Math.PI, 0, 0]}
      />
      <T.Mesh
        name="wax_disk_count001"
        castShadow
        receiveShadow
        geometry={gltf.nodes.wax_disk_count001.geometry}
        material={gltf.materials.panel_and_bottom_details}
        position={[13.59, 0, 0.08]}
        rotation={[-Math.PI, 0, 0]}
      />
      <T.Mesh
        name="wax_disk001"
        castShadow
        receiveShadow
        geometry={gltf.nodes.wax_disk001.geometry}
        material={gltf.materials.panel_and_bottom_details}
        position={[16.42, 4.1, -4.35]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <T.Mesh
        name="plate001"
        castShadow
        receiveShadow
        geometry={gltf.nodes.plate001.geometry}
        material={gltf.materials.panel_and_bottom_details}
        position={[13.59, 0, -11.29]}
        rotation={[-Math.PI, 0, 0]}
      />
      <T.Mesh
        name="tumbler001"
        castShadow
        receiveShadow
        geometry={gltf.nodes.tumbler001.geometry}
        material={gltf.materials.panel_and_bottom_details}
        position={[17.31, 4.66, -8.2]}
        rotation={[0.77, 0.47, -1.14]}
      />
      <T.Mesh
        name="left_needle001"
        castShadow
        receiveShadow
        geometry={gltf.nodes.left_needle001.geometry}
        material={gltf.materials.panel_and_bottom_details}
        position={[16.42, 4.1, -1.69]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <T.Mesh
        name="right_needle001"
        castShadow
        receiveShadow
        geometry={gltf.nodes.right_needle001.geometry}
        material={gltf.materials.panel_and_bottom_details}
        position={[16.42, 4.1, -7.18]}
        rotation={[Math.PI / 2, 0, -Math.PI]}
      />
      
      <T.Mesh
        name="ram_base002"
        castShadow
        receiveShadow
        geometry={gltf.nodes.ram_base002.geometry}
        material={gltf.materials.panel_and_bottom_details}
        position={[11.85, 0.52, 0.18]}
      />
      <T.Mesh
        name="ram_base003"
        castShadow
        receiveShadow
        geometry={gltf.nodes.ram_base003.geometry}
        material={gltf.materials.panel_and_bottom_details}
        position={[12.78, 0.52, 0.18]}
      />
      <T.Mesh
        name="ram_card002"
        castShadow
        receiveShadow
        geometry={gltf.nodes.ram_card002.geometry}
        material={gltf.materials.panel_and_bottom_details}
      />
      <T.Mesh
        name="ram_card003"
        castShadow
        receiveShadow
        geometry={gltf.nodes.ram_card003.geometry}
        material={gltf.materials.panel_and_bottom_details}
      />
      <T.Mesh
        name="key_board_count"
        castShadow
        receiveShadow
        geometry={gltf.nodes.key_board_count.geometry}
        material={gltf.materials.keyboard}
        position={[13.59, 0, 0.08]}
        rotation={[Math.PI, 0, 0]}
      />
      <T.Mesh
        name="key"
        castShadow
        receiveShadow
        geometry={gltf.nodes.key.geometry}
        material={gltf.materials.keyboard}
        position={[19.52, 1.67, 7.47]}
      />
      <T.Mesh
        name="key001"
        castShadow
        receiveShadow
        geometry={gltf.nodes.key001.geometry}
        material={gltf.materials.keyboard}
        position={[19.52, 1.67, 6.12]}
      />
      <T.Mesh
        name="key002"
        castShadow
        receiveShadow
        geometry={gltf.nodes.key002.geometry}
        material={gltf.materials.keyboard}
        position={[19.52, 1.67, 4.78]}
      />
      <T.Mesh
        name="key003"
        castShadow
        receiveShadow
        geometry={gltf.nodes.key003.geometry}
        material={gltf.materials.keyboard}
        position={[19.52, 1.67, 3.43]}
      />
      <T.Mesh
        name="key004"
        castShadow
        receiveShadow
        geometry={gltf.nodes.key004.geometry}
        material={gltf.materials.keyboard}
        position={[19.52, 1.67, 2.09]}
      />
      <T.Mesh
        name="key005"
        castShadow
        receiveShadow
        geometry={gltf.nodes.key005.geometry}
        material={gltf.materials.keyboard}
        position={[19.52, 1.67, 0.74]}
      />
      <T.Mesh
        name="key006"
        castShadow
        receiveShadow
        geometry={gltf.nodes.key006.geometry}
        material={gltf.materials.keyboard}
        position={[19.52, 1.67, -0.6]}
      />
      <T.Mesh
        name="key007"
        castShadow
        receiveShadow
        geometry={gltf.nodes.key007.geometry}
        material={gltf.materials.keyboard}
        position={[19.52, 1.67, -1.95]}
      />
      <T.Mesh
        name="key008"
        castShadow
        receiveShadow
        geometry={gltf.nodes.key008.geometry}
        material={gltf.materials.keyboard}
        position={[19.52, 1.67, -3.29]}
      />
      <T.Mesh
        name="key009"
        castShadow
        receiveShadow
        geometry={gltf.nodes.key009.geometry}
        material={gltf.materials.keyboard}
        position={[19.52, 1.67, -4.64]}
      />
      <T.Mesh
        name="key010"
        castShadow
        receiveShadow
        geometry={gltf.nodes.key010.geometry}
        material={gltf.materials.keyboard}
        position={[19.52, 1.67, -5.98]}
      />
      <T.Mesh
        name="key013"
        castShadow
        receiveShadow
        geometry={gltf.nodes.key013.geometry}
        material={gltf.materials.keyboard}
        position={[20.76, 1.67, 7.16]}
      />
      <T.Mesh
        name="key011"
        castShadow
        receiveShadow
        geometry={gltf.nodes.key011.geometry}
        material={gltf.materials.keyboard}
        position={[20.76, 1.67, 5.82]}
      />
      <T.Mesh
        name="key014"
        castShadow
        receiveShadow
        geometry={gltf.nodes.key014.geometry}
        material={gltf.materials.keyboard}
        position={[20.76, 1.67, 4.47]}
      />
      <T.Mesh
        name="key015"
        castShadow
        receiveShadow
        geometry={gltf.nodes.key015.geometry}
        material={gltf.materials.keyboard}
        position={[20.76, 1.67, 3.14]}
      />
      <T.Mesh
        name="key016"
        castShadow
        receiveShadow
        geometry={gltf.nodes.key016.geometry}
        material={gltf.materials.keyboard}
        position={[20.76, 1.67, 1.8]}
      />
      <T.Mesh
        name="key017"
        castShadow
        receiveShadow
        geometry={gltf.nodes.key017.geometry}
        material={gltf.materials.keyboard}
        position={[20.76, 1.67, 0.45]}
      />
      <T.Mesh
        name="key018"
        castShadow
        receiveShadow
        geometry={gltf.nodes.key018.geometry}
        material={gltf.materials.keyboard}
        position={[20.76, 1.67, -0.91]}
      />
      <T.Mesh
        name="key019"
        castShadow
        receiveShadow
        geometry={gltf.nodes.key019.geometry}
        material={gltf.materials.keyboard}
        position={[20.76, 1.67, -2.25]}
      />
      <T.Mesh
        name="key020"
        castShadow
        receiveShadow
        geometry={gltf.nodes.key020.geometry}
        material={gltf.materials.keyboard}
        position={[20.76, 1.67, -3.59]}
      />
      <T.Mesh
        name="key021"
        castShadow
        receiveShadow
        geometry={gltf.nodes.key021.geometry}
        material={gltf.materials.keyboard}
        position={[20.76, 1.67, -4.94]}
      />
      <T.Mesh
        name="key022"
        castShadow
        receiveShadow
        geometry={gltf.nodes.key022.geometry}
        material={gltf.materials.keyboard}
        position={[20.76, 1.67, -6.28]}
      />
      <T.Mesh
        name="key023"
        castShadow
        receiveShadow
        geometry={gltf.nodes.key023.geometry}
        material={gltf.materials.keyboard}
        position={[20.55, 0.47, 6.09]}
      />
      <T.Mesh
        name="key024"
        castShadow
        receiveShadow
        geometry={gltf.nodes.key024.geometry}
        material={gltf.materials.keyboard}
        position={[20.55, 0.47, 4.72]}
      />
      <T.Mesh
        name="key025"
        castShadow
        receiveShadow
        geometry={gltf.nodes.key025.geometry}
        material={gltf.materials.keyboard}
        position={[20.55, 0.47, 3.37]}
      />
      <T.Mesh
        name="key026"
        castShadow
        receiveShadow
        geometry={gltf.nodes.key026.geometry}
        material={gltf.materials.keyboard}
        position={[20.55, 0.47, 2.04]}
      />
      <T.Mesh
        name="key027"
        castShadow
        receiveShadow
        geometry={gltf.nodes.key027.geometry}
        material={gltf.materials.keyboard}
        position={[20.55, 0.47, 0.68]}
      />
      <T.Mesh
        name="key028"
        castShadow
        receiveShadow
        geometry={gltf.nodes.key028.geometry}
        material={gltf.materials.keyboard}
        position={[20.55, 0.47, -0.67]}
      />
      <T.Mesh
        name="key029"
        castShadow
        receiveShadow
        geometry={gltf.nodes.key029.geometry}
        material={gltf.materials.keyboard}
        position={[20.55, 0.47, -2.01]}
      />
      <T.Mesh
        name="key030"
        castShadow
        receiveShadow
        geometry={gltf.nodes.key030.geometry}
        material={gltf.materials.keyboard}
        position={[20.55, 0.47, -3.36]}
      />
      <T.Mesh
        name="key031"
        castShadow
        receiveShadow
        geometry={gltf.nodes.key031.geometry}
        material={gltf.materials.keyboard}
        position={[20.55, 0.47, -4.67]}
      />
      <T.Mesh
        name="key032"
        castShadow
        receiveShadow
        geometry={gltf.nodes.key032.geometry}
        material={gltf.materials.keyboard}
        position={[20.55, 0.47, -6.01]}
      />
      <T.Mesh
        name="key033"
        castShadow
        receiveShadow
        geometry={gltf.nodes.key033.geometry}
        material={gltf.materials.keyboard}
        position={[20.55, 0.47, -7.36]}
      />
      <T.Mesh
        name="key035"
        castShadow
        receiveShadow
        geometry={gltf.nodes.key035.geometry}
        material={gltf.materials.keyboard}
        position={[23.19, 0.94, 6.47]}
      />
      <T.Mesh
        name="key034"
        castShadow
        receiveShadow
        geometry={gltf.nodes.key034.geometry}
        material={gltf.materials.keyboard}
        position={[23.19, 0.94, 5.1]}
      />
      <T.Mesh
        name="key036"
        castShadow
        receiveShadow
        geometry={gltf.nodes.key036.geometry}
        material={gltf.materials.keyboard}
        position={[23.19, 0.94, 3.75]}
      />
      <T.Mesh
        name="key037"
        castShadow
        receiveShadow
        geometry={gltf.nodes.key037.geometry}
        material={gltf.materials.keyboard}
        position={[23.19, 0.94, 2.41]}
      />
      <T.Mesh
        name="key038"
        castShadow
        receiveShadow
        geometry={gltf.nodes.key038.geometry}
        material={gltf.materials.keyboard}
        position={[23.19, 0.94, 1.05]}
      />
      <T.Mesh
        name="key039"
        castShadow
        receiveShadow
        geometry={gltf.nodes.key039.geometry}
        material={gltf.materials.keyboard}
        position={[23.19, 0.94, -0.29]}
      />
      <T.Mesh
        name="key040"
        castShadow
        receiveShadow
        geometry={gltf.nodes.key040.geometry}
        material={gltf.materials.keyboard}
        position={[23.19, 0.94, -1.65]}
      />
      <T.Mesh
        name="key041"
        castShadow
        receiveShadow
        geometry={gltf.nodes.key041.geometry}
        material={gltf.materials.keyboard}
        position={[23.19, 0.94, -2.98]}
      />
      <T.Mesh
        name="key042"
        castShadow
        receiveShadow
        geometry={gltf.nodes.key042.geometry}
        material={gltf.materials.keyboard}
        position={[23.19, 0.94, -4.31]}
      />
      <T.Mesh
        name="key043"
        castShadow
        receiveShadow
        geometry={gltf.nodes.key043.geometry}
        material={gltf.materials.keyboard}
        position={[23.19, 0.94, -5.65]}
      />
      <T.Mesh
        name="key044"
        castShadow
        receiveShadow
        geometry={gltf.nodes.key044.geometry}
        material={gltf.materials.keyboard}
        position={[23.19, 0.94, -7.04]}
      />
      <T.Mesh
        name="key045"
        castShadow
        receiveShadow
        geometry={gltf.nodes.key045.geometry}
        material={gltf.materials.keyboard}
        position={[21.48, 0.98, 1.1]}
      />
      <T.Mesh
        name="key046"
        castShadow
        receiveShadow
        geometry={gltf.nodes.key046.geometry}
        material={gltf.materials.keyboard}
        position={[19.45, 2.75, -7.75]}
        rotation={[0, 1.57, 0]}
      />
      <T.Mesh
        name="key012"
        castShadow
        receiveShadow
        geometry={gltf.nodes.key012.geometry}
        material={gltf.materials.keyboard}
        position={[21.48, 0.98, 1.1]}
      />
      <T.Mesh
        name="key047"
        castShadow
        receiveShadow
        geometry={gltf.nodes.key047.geometry}
        material={gltf.materials.keyboard}
        position={[22.59, 0.46, 7.34]}
      />
      <T.Mesh
        name="key048"
        castShadow
        receiveShadow
        geometry={gltf.nodes.key048.geometry}
        material={gltf.materials.keyboard}
        position={[22.44, 0.98, -0.74]}
      />
      <T.Mesh
        name="1"
        castShadow
        receiveShadow
        geometry={gltf.nodes['1'].geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[7.02, 2.05, 0.18]}
      />
      <T.Mesh
        name="2"
        castShadow
        receiveShadow
        geometry={gltf.nodes['2'].geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[7.02, 2.05, 0.18]}
      />
      <T.Mesh
        name="4"
        castShadow
        receiveShadow
        geometry={gltf.nodes['4'].geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[7.02, 2.05, 0.18]}
      />
      <T.Mesh
        name="3"
        castShadow
        receiveShadow
        geometry={gltf.nodes['3'].geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[7.02, 2.05, 0.18]}
      />
      <T.Mesh
        name="1_uv_Cylinder029"
        castShadow
        receiveShadow
        geometry={gltf.nodes['1_uv_Cylinder029'].geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[7.02, 2.05, 0.18]}
      />
      <T.Mesh
        name="Cylinder030"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cylinder030.geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[7.02, 2.05, 0.18]}
      />
      <T.Mesh
        name="Cylinder031"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cylinder031.geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[7.02, 2.05, 0.18]}
      />
      <T.Mesh
        name="Cylinder032"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cylinder032.geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[7.02, 2.05, 0.18]}
      />
      <T.Mesh
        name="Cylinder033"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cylinder033.geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[7.02, 2.05, 0.18]}
      />
      <T.Mesh
        name="2side_cable"
        castShadow
        receiveShadow
        geometry={gltf.nodes['2side_cable'].geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[7.02, 2.05, 0.18]}
      />
      <T.Mesh
        name="trans_cable"
        castShadow
        receiveShadow
        geometry={gltf.nodes.trans_cable.geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[8.09, 6.29, 0.18]}
      />
      <T.Mesh
        name="1_uv_clip_b"
        castShadow
        receiveShadow
        geometry={gltf.nodes['1_uv_clip_b'].geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[2.29, 7.62, 0.07]}
      />
      <T.Mesh
        name="clip_b001"
        castShadow
        receiveShadow
        geometry={gltf.nodes.clip_b001.geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[2.29, 7.62, 0.07]}
      />
      <T.Mesh
        name="clip_s001"
        castShadow
        receiveShadow
        geometry={gltf.nodes.clip_s001.geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[2.01, 6.89, -4.22]}
      />
      <T.Mesh
        name="clip_s002"
        castShadow
        receiveShadow
        geometry={gltf.nodes.clip_s002.geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[2.02, 6.89, -6.54]}
      />
      <T.Mesh
        name="clip_s003"
        castShadow
        receiveShadow
        geometry={gltf.nodes.clip_s003.geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[2.01, 6.89, 6.45]}
      />
      <T.Mesh
        name="clip_s004"
        castShadow
        receiveShadow
        geometry={gltf.nodes.clip_s004.geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[2.02, 6.89, 4.13]}
      />
      <T.Mesh
        name="clip_s005"
        castShadow
        receiveShadow
        geometry={gltf.nodes.clip_s005.geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[2.05, 5.01, -3.09]}
        rotation={[-0.86, 0, 0]}
      />
      <T.Mesh
        name="clip_s006"
        castShadow
        receiveShadow
        geometry={gltf.nodes.clip_s006.geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[2.05, 5.01, 3.28]}
        rotation={[-2.24, 0, 0]}
      />
      <T.Mesh
        name="clip_s007"
        castShadow
        receiveShadow
        geometry={gltf.nodes.clip_s007.geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[4.09, 7.37, -6.95]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      />
      <T.Mesh
        name="1_uv_clip_s"
        castShadow
        receiveShadow
        geometry={gltf.nodes['1_uv_clip_s'].geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[4.09, 7.37, 7.13]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      />
      <T.Mesh
        name="1side_c003"
        castShadow
        receiveShadow
        geometry={gltf.nodes['1side_c003'].geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[8.09, 6.29, 0.09]}
      />
      <T.Mesh
        name="1side_c"
        castShadow
        receiveShadow
        geometry={gltf.nodes['1side_c'].geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[2.42, 13.63, 0.13]}
      />
      <T.Mesh
        name="1side_c001"
        castShadow
        receiveShadow
        geometry={gltf.nodes['1side_c001'].geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[2.09, 6.58, 0.09]}
      />
      <T.Mesh
        name="1side_c002"
        castShadow
        receiveShadow
        geometry={gltf.nodes['1side_c002'].geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[2.09, 6.77, 0.09]}
      />
      <T.Mesh
        name="img_set_rope"
        castShadow
        receiveShadow
        geometry={gltf.nodes.img_set_rope.geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[8.09, 6.29, 0.09]}
      />
      <T.Mesh
        name="1_uv_Cylinder058"
        castShadow
        receiveShadow
        geometry={gltf.nodes['1_uv_Cylinder058'].geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[4.42, 1.06, -0.66]}
      />
      <T.Mesh
        name="Cylinder059"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cylinder059.geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[4.42, 1.06, 0.8]}
        rotation={[0, 0.55, 0]}
      />
      <T.Mesh
        name="Cylinder060"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cylinder060.geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[2.48, 1.06, -0.66]}
        rotation={[0, 0.61, 0]}
      />
      <T.Mesh
        name="Cylinder061"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cylinder061.geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[2.45, 1.06, 0.8]}
        rotation={[0, 0.75, 0]}
      />
      <T.Mesh
        name="1_uv_Cylinder062"
        castShadow
        receiveShadow
        geometry={gltf.nodes['1_uv_Cylinder062'].geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[9.97, 20.4, -8.69]}
        rotation={[0, -0.5, 0]}
      />
      <T.Mesh
        name="Cylinder063"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cylinder063.geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[9.97, 20.4, 8.89]}
        rotation={[0, 0.74, 0]}
      />
      <T.Mesh
        name="Cylinder064"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cylinder064.geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[4.05, 17.87, 8.89]}
        rotation={[-Math.PI, 0.97, -Math.PI]}
      />
      <T.Mesh
        name="Cylinder065"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cylinder065.geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[4.1, 17.87, -8.69]}
        rotation={[0, 0.76, 0]}
      />
      <T.Mesh
        name="Cylinder066"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cylinder066.geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[4.1, 7.79, -8.69]}
        rotation={[-Math.PI, 1.21, -Math.PI]}
      />
      <T.Mesh
        name="Cylinder076"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cylinder076.geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[4.05, 7.79, 8.89]}
        rotation={[Math.PI, -0.5, Math.PI]}
      />
      <T.Mesh
        name="Cylinder077"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cylinder077.geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[13.93, 16.11, 8.77]}
        rotation={[-0.74, 0, Math.PI / 2]}
      />
      <T.Mesh
        name="Cylinder078"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cylinder078.geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[13.93, 13.31, 8.77]}
        rotation={[-1.99, 0, Math.PI / 2]}
      />
      <T.Mesh
        name="Cylinder079"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cylinder079.geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[13.93, 10.55, 8.77]}
        rotation={[-0.87, 0, Math.PI / 2]}
      />
      <T.Mesh
        name="Cylinder080"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cylinder080.geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[13.93, 16.11, -8.58]}
        rotation={[-0.74, 0, Math.PI / 2]}
      />
      <T.Mesh
        name="Cylinder081"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cylinder081.geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[13.93, 13.31, -8.58]}
        rotation={[-1.99, 0, Math.PI / 2]}
      />
      <T.Mesh
        name="Cylinder082"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cylinder082.geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[13.93, 10.55, -8.58]}
        rotation={[-0.87, 0, Math.PI / 2]}
      />
      <T.Mesh
        name="Cylinder083"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cylinder083.geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[1.51, 7.79, -0.7]}
        rotation={[Math.PI, -0.36, Math.PI]}
      />
      <T.Mesh
        name="Cylinder084"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cylinder084.geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[1.51, 7.79, 0.91]}
        rotation={[-Math.PI, 0.34, -Math.PI]}
      />
      <T.Mesh
        name="Cylinder085"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cylinder085.geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[1.42, 12.29, 4.93]}
        rotation={[-2.53, 0, -Math.PI / 2]}
      />
      <T.Mesh
        name="Cylinder086"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cylinder086.geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[1.42, 12.29, -4.78]}
        rotation={[-0.52, 0, -Math.PI / 2]}
      />
      <T.Mesh
        name="1_uv_Cube062"
        castShadow
        receiveShadow
        geometry={gltf.nodes['1_uv_Cube062'].geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[0.89, 4.04, -1.46]}
        rotation={[-0.79, 0, Math.PI / 2]}
      />
      <T.Mesh
        name="Cube063"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cube063.geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[0.89, 4.04, 1.45]}
        rotation={[0.54, 0, Math.PI / 2]}
      />
      <T.Mesh
        name="Cube064"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cube064.geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[0.89, 2.31, -1.46]}
        rotation={[0, 0, Math.PI / 2]}
      />
      <T.Mesh
        name="Cube065"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cube065.geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[0.89, 2.31, 1.45]}
        rotation={[-2.14, 0, Math.PI / 2]}
      />
      <T.Mesh
        name="Cube066"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cube066.geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[1.73, 4.56, 3.66]}
        rotation={[-0.54, 0, -Math.PI / 2]}
      />
      <T.Mesh
        name="Cube067"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cube067.geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[1.73, 4.56, 6.35]}
        rotation={[0.09, 0, -Math.PI / 2]}
      />
      <T.Mesh
        name="Cube068"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cube068.geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[1.73, 1.88, 3.66]}
        rotation={[2.57, 0, -Math.PI / 2]}
      />
      <T.Mesh
        name="Cube069"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cube069.geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[1.73, 1.88, 6.35]}
        rotation={[1.94, 0, -Math.PI / 2]}
      />
      <T.Mesh
        name="Cube070"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cube070.geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[1.73, 4.56, -6.19]}
        rotation={[-0.54, 0, -Math.PI / 2]}
      />
      <T.Mesh
        name="Cube071"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cube071.geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[1.73, 4.56, -3.49]}
        rotation={[0.09, 0, -Math.PI / 2]}
      />
      <T.Mesh
        name="Cube072"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cube072.geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[1.73, 1.88, -6.19]}
        rotation={[2.57, 0, -Math.PI / 2]}
      />
      <T.Mesh
        name="Cube073"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cube073.geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[1.73, 1.88, -3.49]}
        rotation={[1.94, 0, -Math.PI / 2]}
      />
      <T.Mesh
        name="Cube075"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cube075.geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[13.8, 4.24, 1.81]}
        rotation={[-0.52, 0, Math.PI / 2]}
      />
      <T.Mesh
        name="Cube077"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cube077.geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[13.8, 3.3, 1.81]}
        rotation={[3.14, 0, Math.PI / 2]}
      />
      <T.Mesh
        name="Cube074"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cube074.geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[13.8, 4.24, -1.6]}
        rotation={[-1.02, 0, Math.PI / 2]}
      />
      <T.Mesh
        name="Cube076"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cube076.geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[13.8, 3.3, -1.6]}
        rotation={[-1.8, 0, Math.PI / 2]}
      />
      <T.Mesh
        name="Cube078"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cube078.geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[0.96, 17.36, -4.85]}
        rotation={[-0.79, 0, Math.PI / 2]}
      />
      <T.Mesh
        name="Cube079"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cube079.geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[0.96, 17.36, -4.23]}
        rotation={[-2.15, 0, Math.PI / 2]}
      />
      <T.Mesh
        name="Cube080"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cube080.geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[0.96, 17.36, 4.41]}
        rotation={[-0.79, 0, Math.PI / 2]}
      />
      <T.Mesh
        name="Cube081"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cube081.geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[0.96, 17.36, 5.04]}
        rotation={[-2.15, 0, Math.PI / 2]}
      />
      <T.Mesh
        name="audio_setting_handle"
        castShadow
        receiveShadow
        geometry={gltf.nodes.audio_setting_handle.geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[8.09, 6.29, 0.09]}
      />
      <T.Mesh
        name="1_uv_screw"
        castShadow
        receiveShadow
        geometry={gltf.nodes['1_uv_screw'].geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[8.09, 6.29, 0.09]}
      />
      <T.Mesh
        name="screw002"
        castShadow
        receiveShadow
        geometry={gltf.nodes.screw002.geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[8.09, 6.29, 0.09]}
      />
      <T.Mesh
        name="screw001"
        castShadow
        receiveShadow
        geometry={gltf.nodes.screw001.geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[8.09, 6.29, 0.09]}
      />
      <T.Mesh
        name="screw004"
        castShadow
        receiveShadow
        geometry={gltf.nodes.screw004.geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[8.09, 6.29, 0.09]}
      />
      <T.Mesh
        name="screw003"
        castShadow
        receiveShadow
        geometry={gltf.nodes.screw003.geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[8.09, 6.29, 0.09]}
      />
      <T.Mesh
        name="screw005"
        castShadow
        receiveShadow
        geometry={gltf.nodes.screw005.geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[8.09, 6.29, 0.09]}
      />
      <T.Mesh
        name="Circle"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Circle.geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[8.09, 6.29, 0.09]}
      />
      <T.Mesh
        name="Circle001"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Circle001.geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[8.09, 6.29, 0.09]}
      />
      <T.Mesh
        name="Cylinder049"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cylinder049.geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[8.09, 6.29, 0.09]}
      />
      <T.Mesh
        name="Cylinder052"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cylinder052.geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[8.09, 6.29, 0.09]}
      />
      <T.Mesh
        name="1_uv_Cube038"
        castShadow
        receiveShadow
        geometry={gltf.nodes['1_uv_Cube038'].geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[8.09, 6.28, 0.09]}
      />
      <T.Mesh
        name="Cube039"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cube039.geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[8.09, 6.28, 0.09]}
      />
      <T.Mesh
        name="roller"
        castShadow
        receiveShadow
        geometry={gltf.nodes.roller.geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[8.09, 6.29, 0.09]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <T.Mesh
        name="roller001"
        castShadow
        receiveShadow
        geometry={gltf.nodes.roller001.geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[8.09, 6.29, 0.09]}
      />
      <T.Mesh
        name="main_img_set_handle"
        castShadow
        receiveShadow
        geometry={gltf.nodes.main_img_set_handle.geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[1.52, 18.52, 0.12]}
      />
      <T.Mesh
        name="1_uv_Cube026"
        castShadow
        receiveShadow
        geometry={gltf.nodes['1_uv_Cube026'].geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[13.57, 16.11, -7.91]}
      />
      <T.Mesh
        name="Cube027"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cube027.geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[13.57, 13.31, -7.91]}
      />
      <T.Mesh
        name="Cube028"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cube028.geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[13.57, 10.55, -7.91]}
      />
      <T.Mesh
        name="Cube029"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cube029.geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[13.57, 16.11, 8.12]}
        rotation={[-Math.PI, 0, 0]}
      />
      <T.Mesh
        name="Cube030"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cube030.geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[13.57, 13.31, 8.12]}
        rotation={[-Math.PI, 0, 0]}
      />
      <T.Mesh
        name="Cube031"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cube031.geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[13.57, 10.55, 8.12]}
        rotation={[-Math.PI, 0, 0]}
      />
      <T.Mesh
        name="label_podium"
        castShadow
        receiveShadow
        geometry={gltf.nodes.label_podium.geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[14, 20.15, 0.02]}
      />
      <T.Mesh
        name="label_count"
        castShadow
        receiveShadow
        geometry={gltf.nodes.label_count.geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[8.11, 6.29, 0.09]}
      />
      <T.Mesh
        name="canvas"
        castShadow
        receiveShadow
        geometry={gltf.nodes.canvas.geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[8.03, 6.29, 0.09]}
      />
      <T.Mesh
        name="canvas_count"
        castShadow
        receiveShadow
        geometry={gltf.nodes.canvas_count.geometry}
        material={gltf.materials.cable_bolt_canvas}
        position={[8.09, 6.29, 0.09]}
      />
      <T.Mesh
        name="speaker"
        castShadow
        receiveShadow
        geometry={gltf.nodes.speaker.geometry}
        material={gltf.materials.disk_and_audio}
        position={[8.09, 6.29, 0.09]}
      />
      <T.Mesh
        name="speaker001"
        castShadow
        receiveShadow
        geometry={gltf.nodes.speaker001.geometry}
        material={gltf.materials.disk_and_audio}
        position={[8.09, 6.29, 0.09]}
      />
      <T.Mesh
        name="speaker_body"
        castShadow
        receiveShadow
        geometry={gltf.nodes.speaker_body.geometry}
        material={gltf.materials.disk_and_audio}
        position={[8.09, 6.29, 0.09]}
      />
      <T.Mesh
        name="disk_body"
        castShadow
        receiveShadow
        geometry={gltf.nodes.disk_body.geometry}
        material={gltf.materials.disk_and_audio}
        position={[4.61, 12.3, 0.09]}
        rotation={[0, 0, -Math.PI / 2]}
      />
      <T.Mesh
        name="disk_rotor"
        castShadow
        receiveShadow
        geometry={gltf.nodes.disk_rotor.geometry}
        material={gltf.materials.disk_and_audio}
        position={[2.32, 12.28, 0.09]}
      />
      <T.Mesh
        name="magnet"
        castShadow
        receiveShadow
        geometry={gltf.nodes.magnet.geometry}
        material={gltf.materials.disk_and_audio}
        position={[1.79, 12.3, 0.09]}
        rotation={[-0.05, 0, Math.PI / 2]}
      />
      <T.Mesh
        name="image_disk"
        castShadow
        receiveShadow
        geometry={gltf.nodes.image_disk.geometry}
        material={gltf.materials.disk_and_audio}
        position={[1.36, 12.3, 0.09]}
      />
      <T.Mesh
        name="rotor_shaft"
        castShadow
        receiveShadow
        geometry={gltf.nodes.rotor_shaft.geometry}
        material={gltf.materials.disk_and_audio}
        position={[3.69, 12.3, 0.09]}
      />
      <T.Mesh
        name="rotor_front_skrew"
        castShadow
        receiveShadow
        geometry={gltf.nodes.rotor_front_skrew.geometry}
        material={gltf.materials.disk_and_audio}
        position={[4.76, 12.3, 0.09]}
      />
      <T.Mesh
        name="rotor_skrew"
        castShadow
        receiveShadow
        geometry={gltf.nodes.rotor_skrew.geometry}
        material={gltf.materials.disk_and_audio}
        position={[1.15, 12.3, 0.09]}
      />
      <T.Mesh
        name="tube_body"
        castShadow
        receiveShadow
        geometry={gltf.nodes.tube_body.geometry}
        material={gltf.materials.disk_and_audio}
        position={[3.27, 14.69, 0.09]}
      />
      <T.Mesh
        name="lins_conect"
        castShadow
        receiveShadow
        geometry={gltf.nodes.lins_conect.geometry}
        material={gltf.materials.disk_and_audio}
        position={[4.19, 15.59, 0.09]}
      />
      <T.Mesh
        name="tube_amp"
        castShadow
        receiveShadow
        geometry={gltf.nodes.tube_amp.geometry}
        material={gltf.materials.disk_and_audio}
        position={[2.04, 14.67, 0.09]}
        rotation={[0, 0, Math.PI / 2]}
      />
      <T.Mesh
        name="s_lins_count"
        castShadow
        receiveShadow
        geometry={gltf.nodes.s_lins_count.geometry}
        material={gltf.materials.disk_and_audio}
        position={[6.09, 14.81, 0.09]}
        rotation={[0, 0, -Math.PI / 2]}
      />
      <T.Mesh
        name="b_lins_count"
        castShadow
        receiveShadow
        geometry={gltf.nodes.b_lins_count.geometry}
        material={gltf.materials.disk_and_audio}
        position={[7.16, 14.81, 0.09]}
        rotation={[0, 0, -Math.PI / 2]}
      />
      <T.Mesh
        name="long_plate"
        castShadow
        receiveShadow
        geometry={gltf.nodes.long_plate.geometry}
        material={gltf.materials.disk_and_audio}
        position={[8.09, 6.29, 0.09]}
      />
      <T.Mesh
        name="2_side_conect"
        castShadow
        receiveShadow
        geometry={gltf.nodes['2_side_conect'].geometry}
        material={gltf.materials.disk_and_audio}
        position={[8.09, 6.29, 0.09]}
      />
      <T.Mesh
        name="conector_big_bolt"
        castShadow
        receiveShadow
        geometry={gltf.nodes.conector_big_bolt.geometry}
        material={gltf.materials.disk_and_audio}
        position={[8.09, 6.29, 0.09]}
      />
      <T.Mesh
        name="rope_conect"
        castShadow
        receiveShadow
        geometry={gltf.nodes.rope_conect.geometry}
        material={gltf.materials.disk_and_audio}
        position={[8.09, 6.29, 0.09]}
      />
      <T.Mesh
        name="disk_x-side_conect"
        castShadow
        receiveShadow
        geometry={gltf.nodes['disk_x-side_conect'].geometry}
        material={gltf.materials.disk_and_audio}
        position={[3.69, 12.3, 0.09]}
      />
      <T.Mesh
        name="disk_y-side_conect"
        castShadow
        receiveShadow
        geometry={gltf.nodes['disk_y-side_conect'].geometry}
        material={gltf.materials.disk_and_audio}
        position={[3.69, 12.3, 0.09]}
      />
      <T.Mesh
        name="disk_cable_conector"
        castShadow
        receiveShadow
        geometry={gltf.nodes.disk_cable_conector.geometry}
        material={gltf.materials.disk_and_audio}
        position={[1.68, 13.53, 0.09]}
      />
      <T.Mesh
        name="rail_body"
        castShadow
        receiveShadow
        geometry={gltf.nodes.rail_body.geometry}
        material={gltf.materials.disk_and_audio}
        position={[4.61, 12.34, 0.09]}
      />
      <T.Mesh
        name="rail_facture"
        castShadow
        receiveShadow
        geometry={gltf.nodes.rail_facture.geometry}
        material={gltf.materials.disk_and_audio}
        position={[4.61, 12.34, 0.09]}
      />
      <T.Mesh
        name="rail_gear"
        castShadow
        receiveShadow
        geometry={gltf.nodes.rail_gear.geometry}
        material={gltf.materials.disk_and_audio}
        position={[1.41, 12.27, 0.09]}
      />
      <T.Mesh
        name="lumen_64"
        castShadow
        receiveShadow
        geometry={gltf.nodes.lumen_64.geometry}
        material={gltf.materials.emis}
        position={[14.52, 19.99, 2.45]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      />
      <T.Mesh
        name="electrod006"
        castShadow
        receiveShadow
        geometry={gltf.nodes.electrod006.geometry}
        material={gltf.materials.emis}
        position={[3.27, 14.67, 0.09]}
      />
      <T.Mesh
        name="indicatorOpen"
        castShadow
        receiveShadow
        geometry={gltf.nodes.indicatorOpen.geometry}
        material={gltf.materials.emis}
        position={[16.17, 5.09, 4.35]}
        rotation={[0, 0, -0.56]}
      />
      <T.Mesh
        name="indicatorBorder"
        castShadow
        receiveShadow
        geometry={gltf.nodes.indicatorBorder.geometry}
        material={gltf.materials.panel_and_bottom_details}
        position={[16.17, 5.09, 4.35]}
        rotation={[0, 0, -0.56]}
      />
      <T.Mesh
        name="indicatorClose"
        castShadow
        receiveShadow
        geometry={gltf.nodes.indicatorClose.geometry}
        material={gltf.materials.panel_and_bottom_details}
        position={[16.17, 5.09, 4.36]}
        rotation={[0, 0, -0.56]}
      />
      <T.Mesh
        name="glass"
        castShadow
        receiveShadow
        geometry={gltf.nodes.glass.geometry}
        material={gltf.materials.glass}
        position={[5.76, 2.25, 5.08]}
      />
      <T.Mesh
        name="glass003"
        castShadow
        receiveShadow
        geometry={gltf.nodes.glass003.geometry}
        material={gltf.materials.glass}
        position={[5.76, 2.25, -4.93]}
      />
      <T.Mesh
        name="glass004"
        castShadow
        receiveShadow
        geometry={gltf.nodes.glass004.geometry}
        material={gltf.materials.glass}
        position={[7.91, 2.25, -4.93]}
      />
      <T.Mesh
        name="glass005"
        castShadow
        receiveShadow
        geometry={gltf.nodes.glass005.geometry}
        material={gltf.materials.glass}
        position={[10.06, 2.25, -4.93]}
      />
      <T.Mesh
        name="glass002"
        castShadow
        receiveShadow
        geometry={gltf.nodes.glass002.geometry}
        material={gltf.materials.glass}
        position={[10.06, 2.25, 5.08]}
      />
      <T.Mesh
        name="glass001"
        castShadow
        receiveShadow
        geometry={gltf.nodes.glass001.geometry}
        material={gltf.materials.glass}
        position={[7.95, 2.25, 5.08]}
      />
      <T.Mesh
        name="electrod"
        castShadow
        receiveShadow
        geometry={gltf.nodes.electrod.geometry}
        material={gltf.materials.emis}
        position={[5.76, 1.95, 5.08]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <T.Mesh
        name="electrod003"
        castShadow
        receiveShadow
        geometry={gltf.nodes.electrod003.geometry}
        material={gltf.materials.emis}
        position={[5.76, 1.95, -4.93]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <T.Mesh
        name="electrod004"
        castShadow
        receiveShadow
        geometry={gltf.nodes.electrod004.geometry}
        material={gltf.materials.emis}
        position={[7.91, 1.95, -4.93]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <T.Mesh
        name="electrod005"
        castShadow
        receiveShadow
        geometry={gltf.nodes.electrod005.geometry}
        material={gltf.materials.emis}
        position={[10.06, 1.95, -4.93]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <T.Mesh
        name="electrod002"
        castShadow
        receiveShadow
        geometry={gltf.nodes.electrod002.geometry}
        material={gltf.materials.emis}
        position={[10.06, 1.95, 5.08]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <T.Mesh
        name="electrod001"
        castShadow
        receiveShadow
        geometry={gltf.nodes.electrod001.geometry}
        material={gltf.materials.emis}
        position={[7.95, 1.95, 5.08]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <T.Mesh
        name="add006"
        castShadow
        receiveShadow
        geometry={gltf.nodes.add006.geometry}
        material={gltf.materials.panel_and_bottom_details}
        position={[5.76, 1.95, 5.08]}
        rotation={[0, -1.57, 0]}
      />
      <T.Mesh
        name="add003"
        castShadow
        receiveShadow
        geometry={gltf.nodes.add003.geometry}
        material={gltf.materials.panel_and_bottom_details}
        position={[5.76, 1.95, -4.93]}
        rotation={[0, -1.57, 0]}
      />
      <T.Mesh
        name="add004"
        castShadow
        receiveShadow
        geometry={gltf.nodes.add004.geometry}
        material={gltf.materials.panel_and_bottom_details}
        position={[7.91, 1.95, -4.93]}
        rotation={[0, -1.57, 0]}
      />
      <T.Mesh
        name="add005"
        castShadow
        receiveShadow
        geometry={gltf.nodes.add005.geometry}
        material={gltf.materials.panel_and_bottom_details}
        position={[10.06, 1.95, -4.93]}
        rotation={[0, -1.57, 0]}
      />
      <T.Mesh
        name="add002"
        castShadow
        receiveShadow
        geometry={gltf.nodes.add002.geometry}
        material={gltf.materials.panel_and_bottom_details}
        position={[10.06, 1.95, 5.08]}
        rotation={[0, -1.57, 0]}
      />
      <T.Mesh
        name="add001"
        castShadow
        receiveShadow
        geometry={gltf.nodes.add001.geometry}
        material={gltf.materials.panel_and_bottom_details}
        position={[7.95, 1.95, 5.08]}
        rotation={[0, -1.57, 0]}
      />
      <T.Mesh
        name="gear006"
        castShadow
        receiveShadow
        geometry={gltf.nodes.gear006.geometry}
        material={gltf.materials.panel_and_bottom_details}
        position={[5.76, 1.95, 5.08]}
      />
      <T.Mesh
        name="gear003"
        castShadow
        receiveShadow
        geometry={gltf.nodes.gear003.geometry}
        material={gltf.materials.panel_and_bottom_details}
        position={[5.76, 1.95, -4.93]}
      />
      <T.Mesh
        name="gear004"
        castShadow
        receiveShadow
        geometry={gltf.nodes.gear004.geometry}
        material={gltf.materials.panel_and_bottom_details}
        position={[7.91, 1.95, -4.93]}
      />
      <T.Mesh
        name="gear005"
        castShadow
        receiveShadow
        geometry={gltf.nodes.gear005.geometry}
        material={gltf.materials.panel_and_bottom_details}
        position={[10.06, 1.95, -4.93]}
      />
      <T.Mesh
        name="gear002"
        castShadow
        receiveShadow
        geometry={gltf.nodes.gear002.geometry}
        material={gltf.materials.panel_and_bottom_details}
        position={[10.06, 1.95, 5.08]}
      />
      <T.Mesh
        name="gear001"
        castShadow
        receiveShadow
        geometry={gltf.nodes.gear001.geometry}
        material={gltf.materials.panel_and_bottom_details}
        position={[7.95, 1.95, 5.08]}
      />
      <T.Mesh
        name="base001"
        castShadow
        receiveShadow
        geometry={gltf.nodes.base001.geometry}
        material={gltf.materials.panel_and_bottom_details}
        position={[5.76, 1.96, 5.08]}
      />
      <T.Mesh
        name="base004"
        castShadow
        receiveShadow
        geometry={gltf.nodes.base004.geometry}
        material={gltf.materials.panel_and_bottom_details}
        position={[5.76, 1.96, -4.93]}
      />
      <T.Mesh
        name="base005"
        castShadow
        receiveShadow
        geometry={gltf.nodes.base005.geometry}
        material={gltf.materials.panel_and_bottom_details}
        position={[7.91, 1.96, -4.93]}
      />
      <T.Mesh
        name="base006"
        castShadow
        receiveShadow
        geometry={gltf.nodes.base006.geometry}
        material={gltf.materials.panel_and_bottom_details}
        position={[10.06, 1.96, -4.93]}
      />
      <T.Mesh
        name="base003"
        castShadow
        receiveShadow
        geometry={gltf.nodes.base003.geometry}
        material={gltf.materials.panel_and_bottom_details}
        position={[10.06, 1.96, 5.08]}
      />
      <T.Mesh
        name="base002"
        castShadow
        receiveShadow
        geometry={gltf.nodes.base002.geometry}
        material={gltf.materials.panel_and_bottom_details}
        position={[7.95, 1.96, 5.08]}
      />
      <T.Mesh
        name="disk_tube_glass"
        castShadow
        receiveShadow
        geometry={gltf.nodes.disk_tube_glass.geometry}
        material={gltf.materials.glass}
        position={[3.27, 14.67, 0.09]}
      />
      <T.Mesh
        name="label_glass"
        castShadow
        receiveShadow
        geometry={gltf.nodes.label_glass.geometry}
        material={gltf.materials.glass}
        position={[8.6, 6.71, 0.09]}
      />
      <T.Mesh
        name="lins_b_glass"
        castShadow
        receiveShadow
        geometry={gltf.nodes.lins_b_glass.geometry}
        material={gltf.materials.glass}
        position={[7.22, 14.81, 0.09]}
        rotation={[0, 0, -Math.PI / 2]}
      />
      <T.Mesh
        name="lins_s_glass"
        castShadow
        receiveShadow
        geometry={gltf.nodes.lins_s_glass.geometry}
        material={gltf.materials.glass}
        position={[6.34, 14.81, 0.09]}
        rotation={[0, 0, -Math.PI / 2]}
      />
      <T.Mesh
        name="cpu_glass"
        castShadow
        receiveShadow
        geometry={gltf.nodes.cpu_glass.geometry}
        material={gltf.materials.glass}
        position={[7.02, 2.02, 0.18]}
        scale={[1.03, 1, 1.03]}
      />
      <T.Mesh
        name="rays_anim"
        castShadow
        receiveShadow
        geometry={gltf.nodes.rays_anim.geometry}
        material={gltf.materials.rays}
        position={[9.25, 13.53, 0.2]}
      />
      <T.Mesh
        name="rays001_opac"
        castShadow
        receiveShadow
        geometry={gltf.nodes.rays001_opac.geometry}
        material={gltf.materials.rays}
        position={[9.17, 13.51, 0.2]}
      />
      <T.Mesh
        name="imagedisk"
        castShadow
        receiveShadow
        geometry={gltf.nodes.imagedisk.geometry}
        material={gltf.materials.image}
        position={[4.71, 14.75, 0.09]}
        rotation={[0, 0, -Math.PI / 2]}
      />
      <T.Mesh
        name="imagedisk_anim"
        castShadow
        receiveShadow
        geometry={gltf.nodes.imagedisk_anim.geometry}
        material={gltf.materials.image}
        position={[4.72, 14.75, 0.09]}
      />
      <T.Mesh
        name="image_monitor"
        castShadow
        receiveShadow
        geometry={gltf.nodes.image_monitor.geometry}
        material={gltf.materials.image}
        position={[14.33, 13.37, 0.09]}
      />
      <T.Mesh
        name="image_monitor_anim"
        castShadow
        receiveShadow
        geometry={gltf.nodes.image_monitor_anim.geometry}
        material={gltf.materials.image}
        position={[14.4, 13.43, 0.12]}
      />
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
